#!/bin/bash

#SBATCH --job-name=PCGNCA-ENV-SETUP
#SBATCH --output=slurm.out
#SBATCH --cpus-per-task=8
#SBATCH --time=06:00:00
#SBATCH --partition=brown
#SBATCH --mail-user=luci@itu.dk,lukr@itu.dk
#SBATCH --mail-type=BEGIN,FAIL,END


"Running on $(hostname)"

conda create --name pcgnca-v2

module load Anaconda3
source /home/data_shares/interactive_nca/.bashrc
source activate pcgnca-v2

conda install pip
pip install -r requirements.txt