#!/bin/bash

#SBATCH --job-name=PCGNCA-EXPERIMENT-8
#SBATCH --output=experiments/ExperimentId-8/slurm.out
#SBATCH --cpus-per-task=32
#SBATCH --time=12:00:00
#SBATCH --partition=red,brown
#SBATCH --mail-user=luci@itu.dk,lukr@itu.dk
#SBATCH --mail-type=BEGIN,FAIL,END

echo "Running on $(hostname)"

module load Anaconda3
source /home/lukr/.bashrc
source activate pcgnca-v4

python3 cli.py --expid 8 --train --n_cores 32 --n_generations 5000 --save_freq 100 --timeout_after "12:00:00" 